language: node_js
node_js:
- node
- '12'
- '10'
- '8'
before_install:
- "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
- npm install -g greenkeeper-lockfile@1
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: oscblgm@gmail.com
  api_key:
    secure: 0s/En+leu9A1MaAbYC1tYxa1eCyiAAAetW20FZrzurx1z3+AGFVcY2obR2xHDgoFnVFQA6UgJ5BKxNrS6MB6FCcyITpgUu+xLt6b0Ny0VncUPdl+d9Iuz5LWUUc7cYaqkEmSaay5fyYm8WyiRmrVmAPGsutqfFW0mRMWF2BI2Vs+pcPd/PgQhqRWVCYTSrZmt8I6NkTwFq3s/6SLPIFo3R79NNwvyxPjjU31/6ywTnhNEzlEjIkhQ3g1QLV6KFwE7oOm+suyyLgh6BhxSABVOoS2DS0joOaajsQgIgScz2VvXBnTtCY/amNitm0E8nCYdDr4iHAZZznbGxIqLPA72GShcO77aB8bymSD2vhW64zd8jiyDP8AiPA9D2stpuM2Nl3Nc2nawwwOU5dwbcXG7lbuf542bZQfvzUMHBJ+3nHZcjgcp5FICiqv824gQFK3XryfAbyBQFRSwbonjnhLXf24wXFHUebprcr+uS/D9ar1Fntm2wp2JgMhsWZzUgUwVwKw8g6GLEsegm7y2GkQPcDVnxeQjASJpX/jVVRtJa/vS85tWGc/YwOuX+QEGKDAsLeoXQqgjOMmcw7a46eR6SMo5+Xz3vlX+tL0ultmDPyX9oHruys4GbTI4mWXPP0/GRFzrmryIIYJk9O2VLTrgmOPoDGWaZ3vP5GEPrBusXI=
  on:
    repo: blgm/jfq
    node: '6'
